server:
  port: 8081
spring:
  datasource:
    driver-class-name:
    url: jdbc:mysql://localhost:3306/spring-security-demo?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
  session:
    store-type: none
security:
  basic:
    enabled: true