server:
  port: 8081
spring:
  datasource:
    driver-class-name:
    url: jdbc:mysql://localhost:3306/spring-security-demo?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
  session:
    store-type: none
security:
  basic:
    enabled: true

custom:
  security:
    browser:
      login-type: JSON
    code:
      image:
        width: 120
        heigth: 45
        expire-in: 120
        length: 6
        hard: 1
        # 哪些url需要校验图片验证码
        filter-urls: /user/*
